### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Caikera** [s-elo/Markdown-editor#1]
By doing `yarn install`, got `ERROR: [Errno 2] No such file or directory: 'install'`

**Comment by s-elo** [comment]
you can just `yarn` to install those dependencies after you install yarn using `npm`.

**Comment by Caikera** [comment]
> you can just `yarn` to install those dependencies after you install yarn using `npm`.

But doing `yarn` I got `ERROR: There are no scenarios; must have at least one.`

**Comment by s-elo** [comment]
what is your environments?

**Comment by Caikera** [comment]
> 

Ubuntu 20.04 on WSL2.

**Comment by s-elo** [comment]
may be you can refer to this [article](http://www.javashuo.com/article/p-djdekgjl-ws.html)

**Comment by Caikera** [comment]
> may be you can refer to this [article](http://www.javashuo.com/article/p-djdekgjl-ws.html)

My `yarn` is installed by `apt-get`. I wonder if there are some other dependency.

**Comment by s-elo** [comment]
what is your node and npm versions?
